export interface Property {
  id: string;
  slug: string;
  name: string;
  location: string;
  area: string;
  beds: number;
  baths: number;
  sleeps: number;
  price: string;
  image: string;
  gallery: string[];
  tag: string;
  badge: string;
  amenities: string[];
  summary: string;
  overview: string;
  sleepingArrangements: string[];
  houseRules: string[];
  nearbyAttractions: string[];
  street?: string;
  unit?: string;
  key?: string;
  matterport?: string;
}

export const properties: Property[] = [
  {
    id: "142533",
    slug: "seafoam",
    name: "Seafoam",
    location: "Topsail Beach, NC",
    area: "Topsail Beach",
    beds: 5,
    baths: 3,
    sleeps: 10,
    price: "$—",
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1505692952047-1a78307da8f2?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1502005229762-cf1b2da7c5d6?auto=format&fit=crop&w=1200&q=80",
    ],
    tag: "Beach Access",
    badge: "Featured",
    amenities: ["Beach Access", "Matterport Tour", "Inquiry Available"],
    summary: "Beach-access Topsail Beach cottage with room for larger groups and a direct inquiry path.",
    overview: "Seafoam is one of the live RTR-backed homes now mapped into the site. We pulled the core occupancy and location data from the visitor listing page, and this page is ready to be enriched further as more RTR detail fields are connected.",
    sleepingArrangements: ["5-bedroom layout from RTR listing", "Detailed bed configuration to be mapped from property detail source"],
    houseRules: ["No smoking", "Minimum age to book: 25", "Check-in 4:00 PM / Check-out 10:00 AM"],
    nearbyAttractions: ["Topsail Beach access", "Local dining", "Island shopping"],
    street: "312 S Anderson Blvd Full Cottage",
    key: "Seafoam",
    matterport: "https://my.matterport.com/show/?m=bPNiK2gUrCF",
  },
  {
    id: "146280",
    slug: "serenity-point-coquina",
    name: "Serenity Point Coquina",
    location: "Topsail Beach, NC",
    area: "Topsail Beach",
    beds: 2,
    baths: 2.5,
    sleeps: 8,
    price: "$—",
    image: "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1505692952047-1a78307da8f2?auto=format&fit=crop&w=1200&q=80",
    ],
    tag: "Beach Access",
    badge: "Featured",
    amenities: ["Beach Access", "Matterport Tour", "Inquiry Available"],
    summary: "Serenity Point Coquina is a Topsail Beach townhome listing now mapped from RTR visitor data.",
    overview: "This is one of the first real RTR properties pulled into the prototype. Core occupancy, bath count, area, address, and Matterport link are now available without waiting for full API integration.",
    sleepingArrangements: ["2-bedroom layout from RTR listing", "More detailed bed layout can be added from full property detail source"],
    houseRules: ["No smoking", "Minimum age to book: 25", "Check-in 4:00 PM / Check-out 10:00 AM"],
    nearbyAttractions: ["Topsail Beach access", "Serenity Point area", "Island dining"],
    street: "2121B Ocean Blvd",
    key: "Coquina",
    matterport: "https://my.matterport.com/show/?m=emWNCafwrVV",
  },
  {
    id: "146282",
    slug: "harbor-house",
    name: "Harbor House",
    location: "Surf City, NC",
    area: "Surf City",
    beds: 3,
    baths: 3,
    sleeps: 9,
    price: "$—",
    image: "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1502005097973-6a7082348e28?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
    ],
    tag: "Beach Access",
    badge: "Popular",
    amenities: ["Beach Access", "Matterport Tour", "Inquiry Available"],
    summary: "Surf City beach-access home with direct inquiry flow and live RTR-based core property metadata.",
    overview: "Harbor House is now fed by real property-list data from the RTR visitor search page. It’s a solid example of how we can replace mock listings with live property references before full availability and rates are connected.",
    sleepingArrangements: ["3-bedroom layout from RTR listing", "Detailed bedding still to be added from deeper source"],
    houseRules: ["No smoking", "Minimum age to book: 25", "Check-in 4:00 PM / Check-out 10:00 AM"],
    nearbyAttractions: ["Surf City dining", "Beach access", "Local shops"],
    street: "1601B N. New River Dr.",
    key: "Harbor House",
    matterport: "https://my.matterport.com/show/?m=JXL6AEzhyGY",
  },
  {
    id: "151270",
    slug: "beach-swans",
    name: "Beach Swans",
    location: "Topsail Beach, NC",
    area: "Topsail Beach",
    beds: 5,
    baths: 3,
    sleeps: 10,
    price: "$—",
    image: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1505692952047-1a78307da8f2?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1502005229762-cf1b2da7c5d6?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
    ],
    tag: "Beach Access",
    badge: "Featured",
    amenities: ["Beach Access", "Matterport Tour", "Inquiry Available"],
    summary: "Larger Topsail Beach home now represented with core live RTR listing data.",
    overview: "Beach Swans is part of the first-pass RTR data mapping. The site now has real listing names, location data, occupancy, and Matterport tour references instead of purely invented placeholders.",
    sleepingArrangements: ["5-bedroom layout from RTR listing"],
    houseRules: ["No smoking", "Minimum age to book: 25", "Check-in 4:00 PM / Check-out 10:00 AM"],
    nearbyAttractions: ["Topsail Beach access", "Local dining", "Island shopping"],
    street: "1002 S Anderson Blvd",
    key: "Beach Swans",
    matterport: "https://my.matterport.com/show/?m=BpgjJpxYHW7",
  },
  {
    id: "162451",
    slug: "aqua-stella",
    name: "Aqua Stella",
    location: "Topsail Beach, NC",
    area: "Topsail Beach",
    beds: 2,
    baths: 2.5,
    sleeps: 6,
    price: "$—",
    image: "https://images.unsplash.com/photo-1505692952047-1a78307da8f2?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1505692952047-1a78307da8f2?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1200&q=80",
    ],
    tag: "Beach Access",
    badge: "Featured",
    amenities: ["Beach Access", "Matterport Tour", "Inquiry Available"],
    summary: "Compact Topsail Beach townhome listing now grounded in real RTR visitor-search data.",
    overview: "Aqua Stella gives us another real property in the prototype, helping the site feel more like actual inventory and less like a concept deck.",
    sleepingArrangements: ["2-bedroom layout from RTR listing"],
    houseRules: ["No smoking", "Minimum age to book: 25", "Check-in 4:00 PM / Check-out 10:00 AM"],
    nearbyAttractions: ["Beach access", "Island dining", "Shopping"],
    street: "2135B Ocean Blvd",
    key: "Aqua Stella",
    matterport: "https://my.matterport.com/show/?m=7Y2iw7kFdnt",
  },
  {
    id: "142522",
    slug: "south-wall-cottage",
    name: "South Wall Cottage",
    location: "Topsail Beach, NC",
    area: "Topsail Beach",
    beds: 2,
    baths: 1,
    sleeps: 5,
    price: "$—",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1502005097973-6a7082348e28?auto=format&fit=crop&w=1200&q=80",
    ],
    tag: "Ocean Front",
    badge: "Oceanfront",
    amenities: ["Ocean Front", "Matterport Tour", "Inquiry Available"],
    summary: "Oceanfront Topsail Beach cottage now seeded from the RTR visitor listing source.",
    overview: "South Wall Cottage adds a stronger oceanfront listing into the site and shows how we can preserve premium positioning even before a full API connection is finished.",
    sleepingArrangements: ["2-bedroom layout from RTR listing"],
    houseRules: ["No smoking", "Minimum age to book: 25", "Check-in 4:00 PM / Check-out 10:00 AM"],
    nearbyAttractions: ["Oceanfront access", "Topsail Beach", "Island dining"],
    street: "1115 Ocean Blvd- South",
    unit: "South",
    key: "Wall South",
    matterport: "https://my.matterport.com/show/?m=BYBsrtSGnCb",
  },
  {
    id: "146278",
    slug: "tahiti-sweetie",
    name: "Tahiti Sweetie",
    location: "Topsail Beach, NC",
    area: "Topsail Beach",
    beds: 4,
    baths: 2,
    sleeps: 8,
    price: "$—",
    image: "https://images.unsplash.com/photo-1502005097973-6a7082348e28?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1502005097973-6a7082348e28?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
    ],
    tag: "Ocean Front",
    badge: "Oceanfront",
    amenities: ["Ocean Front", "Matterport Tour", "Inquiry Available"],
    summary: "Oceanfront Topsail Beach rental with real occupancy data now pulled into the site.",
    overview: "Tahiti Sweetie is part of the first live-data pass from RTR. It helps move the website from concept inventory to recognizable real property inventory.",
    sleepingArrangements: ["4-bedroom layout from RTR listing"],
    houseRules: ["No smoking", "Minimum age to book: 25", "Check-in 4:00 PM / Check-out 10:00 AM"],
    nearbyAttractions: ["Oceanfront access", "Island restaurants", "Topsail Beach attractions"],
    street: "1113 N Anderson",
    key: "Tahiti Sweetie",
    matterport: "https://my.matterport.com/show/?m=kwbrYZ2F4Ed",
  },
  {
    id: "149363",
    slug: "ocean-vibes-ii",
    name: "Ocean Vibes II",
    location: "North Topsail Beach, NC",
    area: "North Topsail Beach",
    beds: 4,
    baths: 3.5,
    sleeps: 12,
    price: "$—",
    image: "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1502005097973-6a7082348e28?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
    ],
    tag: "Ocean Front",
    badge: "Oceanfront",
    amenities: ["Ocean Front", "Matterport Tour", "Inquiry Available"],
    summary: "North Topsail Beach oceanfront home now mapped from live RTR listing data.",
    overview: "Ocean Vibes II brings a higher-capacity North Topsail option into the site using actual visitor-search metadata from RTR.",
    sleepingArrangements: ["4-bedroom layout from RTR listing"],
    houseRules: ["No smoking", "Minimum age to book: 25", "Check-in 4:00 PM / Check-out 10:00 AM"],
    nearbyAttractions: ["Oceanfront access", "North Topsail attractions", "Nearby dining"],
    street: "2356 New River Inlet Dr",
    key: "Ocean Vibes",
    matterport: "https://my.matterport.com/show/?m=q6DixV6sGK1",
  },
  {
    id: "152188",
    slug: "the-crenshaw",
    name: "The Crenshaw",
    location: "Topsail Beach, NC",
    area: "Topsail Beach",
    beds: 2,
    baths: 2.5,
    sleeps: 7,
    price: "$—",
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1502005097973-6a7082348e28?auto=format&fit=crop&w=1200&q=80",
    ],
    tag: "Ocean Front",
    badge: "Oceanfront",
    amenities: ["Ocean Front", "Matterport Tour", "Inquiry Available"],
    summary: "Oceanfront Topsail Beach property now represented with real core listing data from RTR.",
    overview: "The Crenshaw now reflects actual live listing metadata pulled from the RTR visitor search page, including occupancy, baths, location, and Matterport availability.",
    sleepingArrangements: ["2-bedroom layout from RTR listing"],
    houseRules: ["No smoking", "Minimum age to book: 25", "Check-in 4:00 PM / Check-out 10:00 AM"],
    nearbyAttractions: ["Oceanfront access", "Topsail Beach attractions", "Island dining"],
    street: "2107B Ocean Blvd",
    unit: "B",
    key: "The Crenshaw",
    matterport: "https://my.matterport.com/show/?m=5NvFVfCGqTe",
  },
  {
    id: "155754",
    slug: "north-wall-cottage",
    name: "North Wall Cottage",
    location: "Topsail Beach, NC",
    area: "Topsail Beach",
    beds: 2,
    baths: 1,
    sleeps: 4,
    price: "$—",
    image: "https://images.unsplash.com/photo-1505692952047-1a78307da8f2?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1505692952047-1a78307da8f2?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1200&q=80",
    ],
    tag: "Ocean Front",
    badge: "Oceanfront",
    amenities: ["Ocean Front", "Matterport Tour", "Inquiry Available"],
    summary: "Smaller oceanfront cottage now grounded in live RTR visitor-search data.",
    overview: "North Wall Cottage helps round out the first set of real properties in the prototype. It gives the site better variety and more believable inventory depth while we wait on deeper integration.",
    sleepingArrangements: ["2-bedroom layout from RTR listing"],
    houseRules: ["No smoking", "Minimum age to book: 25", "Check-in 4:00 PM / Check-out 10:00 AM"],
    nearbyAttractions: ["Oceanfront access", "Topsail Beach", "Local dining"],
    street: "1115 Ocean Blvd -North",
    unit: "North",
    key: "Wall North",
    matterport: "https://my.matterport.com/show/?m=5CkBPQYTHxJ",
  },
];

export function getPropertyBySlug(slug: string) {
  return properties.find((property) => property.slug === slug);
}
